### ISSUE TITLE
requirements outdated

### ISSUE THREAD

**Issue by saladpanda** [jonny1102/nmap-parse#4]
Hi,
your tool sounds very interesting and I'd like to try it.
But when starting I get this Error:
```
$ ./nmap-parse.py --help
Traceback (most recent call last):
  File "./nmap-parse.py", line 18, in <module>
    from modules import interactive
  File "/home/kali/pentest-stuff/nmap-parse/modules/interactive.py", line 10, in <module>
    from cmd2.argparse_completer import ACArgumentParser, ACTION_ARG_CHOICES, AutoCompleter
ImportError: cannot import name 'ACArgumentParser' from 'cmd2.argparse_completer' (/home/kali/.local/lib/python3.7/site-packages/cmd2/argparse_completer.py)
```

python-cmd2's changelog for v0.9.15 says:
> ACArgumentParser is now called Cmd2ArgumentParser

I fixed this by changing the requirements.txt to contain `cmd2==0.914`.

Now I get:
```
Traceback (most recent call last):
  File "./nmap-parse.py", line 18, in <module>
    from modules import interactive
  File "/home/kali/pentest-stuff/nmap-parse/modules/interactive.py", line 22, in <module>
    @cmd2_submenu.AddSubmenu(nessus.NessusTerminal(),
  File "/home/kali/pentest-stuff/nmap-parse/modules/nessus.py", line 29, in __init__
    super().__init__(*args, **kwargs)
  File "/home/kali/pentest-stuff/nmap-parse/modules/common.py", line 339, in __init__
    super().__init__(*args, **kwargs)
  File "/home/kali/pentest-stuff/nmap-parse/modules/common.py", line 104, in __init__
    self.setupUserOptions()
  File "/home/kali/pentest-stuff/nmap-parse/modules/common.py", line 122, in setupUserOptions
    self.settable[userOption[0]] = userOption[3]
AttributeError: 'NessusTerminal' object has no attribute 'settable'
```

**Comment by saladpanda** [comment]
I checked the date you last changed the requirements.txt and got nmap-parse working using the following requirements.txt:

```
IPy
tabulate
bs4
cmd2==0.9.10
cmd2-submenu==0.3.0
colorama
requests
urllib3
```
